### ISSUE TITLE
Avoid content re-load when perfoming "back" action in browser

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#10]
Tab content reloads when user performs a "back" navigation action in browser (web, mobile). 
Avoid by caching content per session if possible.

**Comment by CodingCarlos** [comment]
Well, this is going to be free, since I've enabled a starter cache version for the full-screen person view, so... Free stuff! :rofl: 

Actually, the project seems to became bigger than initially expected (and I love to see that), so maybe in next iterations we might check Vuex to manage state, and implements by default a cache much better than my approach.
