### ISSUE TITLE
User Profile Company/Org not linked to the right name

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#52]
When company/org name is updated, user's profile still show old name (example: Edu Duque and "Campus Madrid" - it should be "Google for Startups")

**Comment by CodingCarlos** [comment]
Hummm I'm pretty sure that's a backend issue. As far as I've just checked out, it's getting the default sheet value, instead of populating the data from the real company field.

https://github.com/CampusMadridProjects/directory-backend/blob/master/components/people/index.js#L74

I'm updating the sheet now, and adding this issue to the backend repo, to make sure that we improve and fix this issue in the API refactor needed for the dashboard ;)
